### ISSUE TITLE
Support JIT-downloading JLLs

### ISSUE THREAD

**Issue by staticfloat** [staticfloat/sandbox-buildkite-plugin#17]
We could get rid of a couple of the rootfs images we maintain by encoding a list of JLLs that should be downloaded and then providing paths that they should be mounted at.  Example:

```
steps:
  - label: "run code within a sandbox"
    plugins:
      # Install Julia v1.6+ to run sandbox
      - JuliaCI/julia#v1:
          version: 1.6
      - staticfloat/sandbox:
          rootfs_url: "https://github.com/staticfloat/Sandbox.jl/releases/download/debian-minimal-927c9e7f/debian_minimal.tar.gz"
          rootfs_treehash: "5b44fab874ec426cad9b80b7dffd2b3f927c9e7f"
          artifacts:
            - repo: "CMake_jll#v3.22.2+0"
              path: "/usr/local"
            - repo: "https://github.com/JuliaBinaryWrappers/GCCBootstrap_jll.jl#1c237cf7be1a3732ca738f1dc1f34315d5130b30"
              artifacts:
                - "GCCBootstrap"
                - "SomeOtherArtifactName"
              path: "/usr/local"
            - repo: "CUDA_jll#11.7.0+0"
              path: "/usr/cuda"
    commands: |
      echo "this is running in a sandbox!"
```

This would download the specified packages, get their `Artifacts.toml` files, download the specified artifacts, and pass the artifacts in to be mounted.  If you specify artifact names, it allows simultaneously erroring out if such an artifact is not found (e.g. incomplete platform coverage) and downloading of lazy artifacts.
